import { createStore } from 'vuex';

const store = createStore({
  state: () => ({
    surveys: [
      {
        survey_id: '1',
        date: '2022-04-18',
        title: 'Family 1',
        village: 'Micani',
        technology: 'Kitchen',
        text: 'Hier kann eine Beschreibung zu Umfrage 1 stehen',
        src: 'src/static/aktionSodisBig.png',
      },
      {
        survey_id: '2',
        date: '2022-04-19',
        title: 'Family 2',
        village: 'Micani',
        technology: 'Toilet',
        text: 'Hier kann eine Beschreibung zu Umfrage 2 stehen',
        src: 'src/static/aktionSodisBig.png',
      },
      {
        survey_id: '3',
        date: '2022-04-20',
        title: 'Umfrage 3',
        village: 'Micani',
        technology: 'Toilet',
        text: 'Hier kann eine Beschreibung zu Umfrage 3 stehen',
        src: 'src/static/aktionSodisBig.png',
      },
      {
        survey_id: '3',
        date: '2022-04-21',
        title: 'Umfrage 3',
        village: 'Micani',
        technology: 'Toilet',
        text: 'Hier kann eine Beschreibung zu Umfrage 3 stehen',
        src: 'src/static/aktionSodisBig.png',
      },
      {
        survey_id: '3',
        date: '2022-04-22',
        title: 'Umfrage 3',
        village: 'Micani',
        technology: 'Toilet',
        text: 'Hier kann eine Beschreibung zu Umfrage 3 stehen',
        src: 'src/static/aktionSodisBig.png',
      },
      {
        survey_id: '3',
        date: '2022-04-23',
        title: 'Umfrage 3',
        village: 'Micani',
        technology: 'Toilet',
        text: 'Hier kann eine Beschreibung zu Umfrage 3 stehen',
        src: 'src/static/aktionSodisBig.png',
      },
      {
        survey_id: '3',
        date: '2022-04-24',
        title: 'Umfrage 3',
        village: 'Micani',
        technology: 'Toilet',
        text: 'Hier kann eine Beschreibung zu Umfrage 3 stehen',
        src: 'src/static/aktionSodisBig.png',
      },
      {
        survey_id: '3',
        date: '2022-04-22',
        title: 'Umfrage 3',
        village: 'Micani',
        technology: 'Toilet',
        text: 'Hier kann eine Beschreibung zu Umfrage 3 stehen',
        src: 'src/static/aktionSodisBig.png',
      },
      {
        survey_id: '3',
        date: '2022-04-23',
        title: 'Umfrage 3',
        village: 'Micani',
        technology: 'Toilet',
        text: 'Hier kann eine Beschreibung zu Umfrage 3 stehen',
        src: 'src/static/aktionSodisBig.png',
      },
      {
        survey_id: '3',
        date: '2022-04-24',
        title: 'Umfrage 3',
        village: 'Micani',
        technology: 'Toilet',
        text: 'Hier kann eine Beschreibung zu Umfrage 3 stehen',
        src: 'src/static/aktionSodisBig.png',
      },
      {
        survey_id: '3',
        date: '2022-04-22',
        title: 'Umfrage 3',
        village: 'Micani',
        technology: 'Toilet',
        text: 'Hier kann eine Beschreibung zu Umfrage 3 stehen',
        src: 'src/static/aktionSodisBig.png',
      },
      {
        survey_id: '3',
        date: '2022-04-22',
        title: 'Umfrage 3',
        village: 'Micani',
        technology: 'Toilet',
        text: 'Hier kann eine Beschreibung zu Umfrage 3 stehen',
        src: 'src/static/aktionSodisBig.png',
      },
      {
        survey_id: '3',
        date: '2022-04-23',
        title: 'Umfrage 3',
        village: 'Micani',
        technology: 'Toilet',
        text: 'Hier kann eine Beschreibung zu Umfrage 3 stehen',
        src: 'src/static/aktionSodisBig.png',
      },
      {
        survey_id: '3',
        date: '2022-04-24',
        title: 'Umfrage 3',
        village: 'Micani',
        technology: 'Toilet',
        text: 'Hier kann eine Beschreibung zu Umfrage 3 stehen',
        src: 'src/static/aktionSodisBig.png',
      },
      {
        survey_id: '3',
        date: '2022-04-22',
        title: 'Umfrage 3',
        village: 'Micani',
        technology: 'Toilet',
        text: 'Hier kann eine Beschreibung zu Umfrage 3 stehen',
        src: 'src/static/aktionSodisBig.png',
      },
      {
        survey_id: '3',
        date: '2022-04-22',
        title: 'Umfrage 3',
        village: 'Micani',
        technology: 'Toilet',
        text: 'Hier kann eine Beschreibung zu Umfrage 3 stehen',
        src: 'src/static/aktionSodisBig.png',
      },
      {
        survey_id: '3',
        date: '2022-04-23',
        title: 'Umfrage 3',
        village: 'Micani',
        technology: 'Toilet',
        text: 'Hier kann eine Beschreibung zu Umfrage 3 stehen',
        src: 'src/static/aktionSodisBig.png',
      },
      {
        survey_id: '3',
        date: '2022-04-24',
        title: 'Umfrage 3',
        village: 'Micani',
        technology: 'Toilet',
        text: 'Hier kann eine Beschreibung zu Umfrage 3 stehen',
        src: 'src/static/aktionSodisBig.png',
      },
      {
        survey_id: '3',
        date: '2022-04-22',
        title: 'Umfrage 3',
        village: 'Micani',
        technology: 'Toilet',
        text: 'Hier kann eine Beschreibung zu Umfrage 3 stehen',
        src: 'src/static/aktionSodisBig.png',
      },
      {
        survey_id: '3',
        date: '2022-04-23',
        title: 'Umfrage 3',
        village: 'Micani',
        technology: 'Toilet',
        text: 'Hier kann eine Beschreibung zu Umfrage 3 stehen',
        src: 'src/static/aktionSodisBig.png',
      },
      {
        survey_id: '3',
        date: '2022-04-24',
        title: 'Umfrage 3',
        village: 'Micani',
        technology: 'Toilet',
        text: 'Hier kann eine Beschreibung zu Umfrage 3 stehen',
        src: 'src/static/aktionSodisBig.png',
      },
      {
        survey_id: '3',
        date: '2022-04-22',
        title: 'Umfrage 3',
        village: 'Micani',
        technology: 'Toilet',
        text: 'Hier kann eine Beschreibung zu Umfrage 3 stehen',
        src: 'src/static/aktionSodisBig.png',
      },
      {
        survey_id: '3',
        date: '2022-04-22',
        title: 'Umfrage 3',
        village: 'Micani',
        technology: 'Toilet',
        text: 'Hier kann eine Beschreibung zu Umfrage 3 stehen',
        src: 'src/static/aktionSodisBig.png',
      },
      {
        survey_id: '3',
        date: '2022-04-23',
        title: 'Umfrage 3',
        village: 'Micani',
        technology: 'Toilet',
        text: 'Hier kann eine Beschreibung zu Umfrage 3 stehen',
        src: 'src/static/aktionSodisBig.png',
      },
      {
        survey_id: '3',
        date: '2022-04-24',
        title: 'Umfrage 3',
        village: 'Micani',
        technology: 'Toilet',
        text: 'Hier kann eine Beschreibung zu Umfrage 3 stehen',
        src: 'src/static/aktionSodisBig.png',
      },
      {
        survey_id: '3',
        date: '2022-04-22',
        title: 'Umfrage 3',
        village: 'Micani',
        technology: 'Toilet',
        text: 'Hier kann eine Beschreibung zu Umfrage 3 stehen',
        src: 'src/static/aktionSodisBig.png',
      },
      {
        survey_id: '3',
        date: '2022-04-22',
        title: 'Umfrage 3',
        village: 'Micani',
        technology: 'Toilet',
        text: 'Hier kann eine Beschreibung zu Umfrage 3 stehen',
        src: 'src/static/aktionSodisBig.png',
      },
      {
        survey_id: '3',
        date: '2022-04-23',
        title: 'Umfrage 3',
        village: 'Micani',
        technology: 'Toilet',
        text: 'Hier kann eine Beschreibung zu Umfrage 3 stehen',
        src: 'src/static/aktionSodisBig.png',
      },
      {
        survey_id: '3',
        date: '2022-04-24',
        title: 'Umfrage 3',
        village: 'Micani',
        technology: 'Toilet',
        text: 'Hier kann eine Beschreibung zu Umfrage 3 stehen',
        src: 'src/static/aktionSodisBig.png',
      },
      {
        survey_id: '3',
        date: '2022-04-22',
        title: 'Umfrage 3',
        village: 'Micani',
        technology: 'Toilet',
        text: 'Hier kann eine Beschreibung zu Umfrage 3 stehen',
        src: 'src/static/aktionSodisBig.png',
      },
    ],
    questions: [
      {
        question_id: 1,
        question_text: "Wie geht's?",
        question_answer: "gut",
        question_type: "image",
      },
      {
        question_id: "2abs",
        question_text:
          "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis p",
        question_answer: "Nein",
        question_type: "text",
      },
      {
        question_id: 3,
        question_text: "Machst du viel Sport?",
        question_answer: "Nein",
        question_type: "text",
      },
      {
        question_id: 4,
        question_text: "Kannst du schwimmen?",
        question_answer: "Nein",
        question_type: "text",
      },
      {
        question_id: 5,
        question_text: "Kannst du kochen?",
        question_answer: "Nein",
        question_type: "text",
      },
      {
        question_id: 6,
        question_text: "Wie geht's?",
        question_answer: "gut",
        question_type: "text",
      },
      {
        question_id: "2abs",
        question_text: "Trinkst du ausreichend Wasser?",
        question_answer: "Nein",
        question_type: "text",
      },
      {
        question_id: 7,
        question_text: "Machst du viel Sport?",
        question_answer: "Nein",
        question_type: "text",
      },
      {
        question_id: 8,
        question_text: "Kannst du schwimmen?",
        question_answer: "Nein",
        question_type: "text",
      },
      {
        question_id: 9,
        question_text: "Kannst du kochen?",
        question_answer: "Nein",
        question_type: "text",
      },
      {
        question_id: 10,
        question_text: "Wie geht's?",
        question_answer: "gut",
        question_type: "text",
      },
      {
        question_id: "11",
        question_text: "Trinkst du ausreichend Wasser?",
        question_answer: "Nein",
        question_type: "text",
      },
      {
        question_id: 12,
        question_text: "Machst du viel Sport?",
        question_answer: "Nein",
        question_type: "text",
      },
      {
        question_id: 13,
        question_text: "Kannst du schwimmen?",
        question_answer: "Nein",
        question_type: "text",
      },
      {
        question_id: 14,
        question_text: "Kannst du kochen?",
        question_answer: "Nein",
        question_type: "text",
      },
    ],
  }),
});

export default store;
