const surveyData = {
    state: () => ({
        surveys: [
            {
                survey_id: '1',
                date: '2022-04-18',
                title: 'Family 1',
                village: 'Micani',
                technology: 'Kitchen',
                text: 'Hier kann eine Beschreibung zu Umfrage 1 stehen',
                src: 'src/static/aktionSodisBig.png',
            },
            {
                survey_id: '2',
                date: '2022-04-19',
                title: 'Family 2',
                village: 'Micani',
                technology: 'Toilet',
                text: 'Hier kann eine Beschreibung zu Umfrage 2 stehen',
                src: 'src/static/aktionSodisBig.png',
            },
            {
                survey_id: '3',
                date: '2022-04-20',
                title: 'Umfrage 3',
                village: 'Micani',
                technology: 'Toilet',
                text: 'Hier kann eine Beschreibung zu Umfrage 3 stehen',
                src: 'src/static/aktionSodisBig.png',
            },
            {
                survey_id: '3',
                date: '2022-04-21',
                title: 'Umfrage 3',
                village: 'Micani',
                technology: 'Toilet',
                text: 'Hier kann eine Beschreibung zu Umfrage 3 stehen',
                src: 'src/static/aktionSodisBig.png',
            },
            {
                survey_id: '3',
                date: '2022-04-22',
                title: 'Umfrage 3',
                village: 'Micani',
                technology: 'Toilet',
                text: 'Hier kann eine Beschreibung zu Umfrage 3 stehen',
                src: 'src/static/aktionSodisBig.png',
            },
            {
                survey_id: '3',
                date: '2022-04-23',
                title: 'Umfrage 3',
                village: 'Micani',
                technology: 'Toilet',
                text: 'Hier kann eine Beschreibung zu Umfrage 3 stehen',
                src: 'src/static/aktionSodisBig.png',
            },
            {
                survey_id: '3',
                date: '2022-04-24',
                title: 'Umfrage 3',
                village: 'Micani',
                technology: 'Toilet',
                text: 'Hier kann eine Beschreibung zu Umfrage 3 stehen',
                src: 'src/static/aktionSodisBig.png',
            },
            {
                survey_id: '3',
                date: '2022-04-22',
                title: 'Umfrage 3',
                village: 'Micani',
                technology: 'Toilet',
                text: 'Hier kann eine Beschreibung zu Umfrage 3 stehen',
                src: 'src/static/aktionSodisBig.png',
            },
            {
                survey_id: '3',
                date: '2022-04-23',
                title: 'Umfrage 3',
                village: 'Micani',
                technology: 'Toilet',
                text: 'Hier kann eine Beschreibung zu Umfrage 3 stehen',
                src: 'src/static/aktionSodisBig.png',
            },
            {
                survey_id: '3',
                date: '2022-04-24',
                title: 'Umfrage 3',
                village: 'Micani',
                technology: 'Toilet',
                text: 'Hier kann eine Beschreibung zu Umfrage 3 stehen',
                src: 'src/static/aktionSodisBig.png',
            },
            {
                survey_id: '3',
                date: '2022-04-22',
                title: 'Umfrage 3',
                village: 'Micani',
                technology: 'Toilet',
                text: 'Hier kann eine Beschreibung zu Umfrage 3 stehen',
                src: 'src/static/aktionSodisBig.png',
            },
            {
                survey_id: '3',
                date: '2022-04-22',
                title: 'Umfrage 3',
                village: 'Micani',
                technology: 'Toilet',
                text: 'Hier kann eine Beschreibung zu Umfrage 3 stehen',
                src: 'src/static/aktionSodisBig.png',
            },
            {
                survey_id: '3',
                date: '2022-04-23',
                title: 'Umfrage 3',
                village: 'Micani',
                technology: 'Toilet',
                text: 'Hier kann eine Beschreibung zu Umfrage 3 stehen',
                src: 'src/static/aktionSodisBig.png',
            },
            {
                survey_id: '3',
                date: '2022-04-24',
                title: 'Umfrage 3',
                village: 'Micani',
                technology: 'Toilet',
                text: 'Hier kann eine Beschreibung zu Umfrage 3 stehen',
                src: 'src/static/aktionSodisBig.png',
            },
            {
                survey_id: '3',
                date: '2022-04-22',
                title: 'Umfrage 3',
                village: 'Micani',
                technology: 'Toilet',
                text: 'Hier kann eine Beschreibung zu Umfrage 3 stehen',
                src: 'src/static/aktionSodisBig.png',
            },
            {
                survey_id: '3',
                date: '2022-04-22',
                title: 'Umfrage 3',
                village: 'Micani',
                technology: 'Toilet',
                text: 'Hier kann eine Beschreibung zu Umfrage 3 stehen',
                src: 'src/static/aktionSodisBig.png',
            },
            {
                survey_id: '3',
                date: '2022-04-23',
                title: 'Umfrage 3',
                village: 'Micani',
                technology: 'Toilet',
                text: 'Hier kann eine Beschreibung zu Umfrage 3 stehen',
                src: 'src/static/aktionSodisBig.png',
            },
            {
                survey_id: '3',
                date: '2022-04-24',
                title: 'Umfrage 3',
                village: 'Micani',
                technology: 'Toilet',
                text: 'Hier kann eine Beschreibung zu Umfrage 3 stehen',
                src: 'src/static/aktionSodisBig.png',
            },
            {
                survey_id: '3',
                date: '2022-04-22',
                title: 'Umfrage 3',
                village: 'Micani',
                technology: 'Toilet',
                text: 'Hier kann eine Beschreibung zu Umfrage 3 stehen',
                src: 'src/static/aktionSodisBig.png',
            },
            {
                survey_id: '3',
                date: '2022-04-23',
                title: 'Umfrage 3',
                village: 'Micani',
                technology: 'Toilet',
                text: 'Hier kann eine Beschreibung zu Umfrage 3 stehen',
                src: 'src/static/aktionSodisBig.png',
            },
            {
                survey_id: '3',
                date: '2022-04-24',
                title: 'Umfrage 3',
                village: 'Micani',
                technology: 'Toilet',
                text: 'Hier kann eine Beschreibung zu Umfrage 3 stehen',
                src: 'src/static/aktionSodisBig.png',
            },
            {
                survey_id: '3',
                date: '2022-04-22',
                title: 'Umfrage 3',
                village: 'Micani',
                technology: 'Toilet',
                text: 'Hier kann eine Beschreibung zu Umfrage 3 stehen',
                src: 'src/static/aktionSodisBig.png',
            },
            {
                survey_id: '3',
                date: '2022-04-22',
                title: 'Umfrage 3',
                village: 'Micani',
                technology: 'Toilet',
                text: 'Hier kann eine Beschreibung zu Umfrage 3 stehen',
                src: 'src/static/aktionSodisBig.png',
            },
            {
                survey_id: '3',
                date: '2022-04-23',
                title: 'Umfrage 3',
                village: 'Micani',
                technology: 'Toilet',
                text: 'Hier kann eine Beschreibung zu Umfrage 3 stehen',
                src: 'src/static/aktionSodisBig.png',
            },
            {
                survey_id: '3',
                date: '2022-04-24',
                title: 'Umfrage 3',
                village: 'Micani',
                technology: 'Toilet',
                text: 'Hier kann eine Beschreibung zu Umfrage 3 stehen',
                src: 'src/static/aktionSodisBig.png',
            },
            {
                survey_id: '3',
                date: '2022-04-22',
                title: 'Umfrage 3',
                village: 'Micani',
                technology: 'Toilet',
                text: 'Hier kann eine Beschreibung zu Umfrage 3 stehen',
                src: 'src/static/aktionSodisBig.png',
            },
            {
                survey_id: '3',
                date: '2022-04-22',
                title: 'Umfrage 3',
                village: 'Micani',
                technology: 'Toilet',
                text: 'Hier kann eine Beschreibung zu Umfrage 3 stehen',
                src: 'src/static/aktionSodisBig.png',
            },
            {
                survey_id: '3',
                date: '2022-04-23',
                title: 'Umfrage 3',
                village: 'Micani',
                technology: 'Toilet',
                text: 'Hier kann eine Beschreibung zu Umfrage 3 stehen',
                src: 'src/static/aktionSodisBig.png',
            },
            {
                survey_id: '3',
                date: '2022-04-24',
                title: 'Umfrage 3',
                village: 'Micani',
                technology: 'Toilet',
                text: 'Hier kann eine Beschreibung zu Umfrage 3 stehen',
                src: 'src/static/aktionSodisBig.png',
            },
            {
                survey_id: '3',
                date: '2022-04-22',
                title: 'Umfrage 3',
                village: 'Micani',
                technology: 'Toilet',
                text: 'Hier kann eine Beschreibung zu Umfrage 3 stehen',
                src: 'src/static/aktionSodisBig.png',
            },
        ],
    }),
}

export default surveyData;